version: "3.9"
services:
  # container with nginx
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./app:/var/www/app
    ports:
      - "8080:80"
    environment:
      - NGINX_HOST=speaker.com
      - NGINX_PORT=80
  # container with php-fpm (soon)
  pg:
    image: postgres:latest
    container_name: pg
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: speaker
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: root@root.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "8081:80"

